trigger:
- master

parameters:
  - name: branch
    displayName: Nome da branch
    type: string

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  displayName: 'Selecionando a versão 3.7 do Python'
  inputs:
    versionSpec: '3.7'
    addToPath: true
    architecture: 'x64'
- task: DownloadPipelineArtifact@2
  displayName: 'Instalando GitPython'
  inputs:
    buildType: 'current'
    artifactName: 'GitPython'
    targetPath: '$(Pipeline.Workspace)'
- task: PythonScript@0
  displayName: 'Executando script'
  inputs:
    scriptSource: 'filePath'
    scriptPath: criar-pull-requests.py
    arguments: ${{ parameters.branch }}
