trigger:
- master

parameters:
  - name: branch
    displayName: Nome da branch
    type: string

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'ls'
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: criar-pull-request.py
    arguments: ${{ parameters.branch }}
